name: google_sign_in_for_perception
description: An aspect of perception for signing in with a Google account.
version: 0.0.0-a1
publish_to: none

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

google_sign_in: ^6.1.4

dependencies:
  flutter:
    sdk: flutter
  
  abstractions:
    git: https://github.com/enspyrco/abstractions
  locator_for_perception:
    git: https://github.com/enspyrco/locator_for_perception
  
  json_utils:
    git: https://github.com/enspyrco/json_utils

dev_dependencies:
  flutter_test:
    sdk: flutter
  enspyr_lints:
    git: https://github.com/enspyrco/enspyr_lints
